# Site settings
title: Fabio Piras's portafolio
description: Portafolio for Fabio Piras
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Fabio Piras
user_description: Ingegnere informatico, laureato all'università di Pisa
user_title: Studente in computer engineering curriculum cybersecurity
email: fabizen99@gmai.cm
twitter_username: lorem_ipsum
github_username:  Albran99
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
